version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: events-app-php
        volumes:
            - .:/var/www
        depends_on:
            - db
        expose:
            - 9000
            - 9003
        extra_hosts:
            - "host.docker.internal:host-gateway"

    db:
        image: postgres:15
        container_name: events-app-db
        restart: always
        environment:
            POSTGRES_DB: events_db
            POSTGRES_USER: events_user
            POSTGRES_PASSWORD: password
        ports:
            - "5437:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

    nginx:
        image: nginx:alpine
        container_name: events-nginx
        ports:
            - "8005:80"
        volumes:
            - .:/var/www
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

volumes:
    pgdata:
